import type {ReactNode} from 'react';
import Link from '@docusaurus/Link';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';
import CodeBlock from '@theme/CodeBlock';
import Head from '@docusaurus/Head';
import useBaseUrl from '@docusaurus/useBaseUrl';
import styles from './index.module.css';

const CONSOLE_URL = 'https://console.mfe-orchestrator.dev';
const GITHUB_URL = 'https://github.com/mfe-orchestrator';
const SITE_URL = 'https://mfe-orchestrator.dev';
const DOCS_URL = `${SITE_URL}/documentation/`;

const ORGANIZATION = {
  '@type': 'Organization',
  name: 'MFE Orchestrator',
  url: SITE_URL,
  logo: `${DOCS_URL}img/logo.png`,
  sameAs: [GITHUB_URL],
};

// Emitted only on the documentation home: describes the site as a whole and
// the product it documents. Individual doc pages emit TechArticle instead.
const STRUCTURED_DATA = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebSite',
      '@id': `${DOCS_URL}#website`,
      name: 'MFE Orchestrator documentation',
      url: DOCS_URL,
      description:
        'Documentation for MFE Orchestrator: the control plane for microfrontend architectures.',
      inLanguage: 'en',
      publisher: ORGANIZATION,
    },
    {
      '@type': 'SoftwareApplication',
      name: 'MFE Orchestrator',
      applicationCategory: 'DeveloperApplication',
      operatingSystem: 'Any',
      url: SITE_URL,
      description:
        'Control plane for microfrontend architectures: versions, environments, deployments and ' +
        'rollbacks, with generated Module Federation configuration. Hosted or self-hosted.',
      author: ORGANIZATION,
      publisher: ORGANIZATION,
    },
  ],
};

const HOST_CONFIG = `// vite.config.js — generated by MFE Orchestrator
import { defineConfig } from 'vite';
import federation from '@originjs/vite-plugin-federation';

export default defineConfig({
  plugins: [
    federation({
      name: 'shell',
      filename: 'remoteEntry.js',
      remotes: {
        catalog: {
          external: \`import('@mfe-orchestrator-hub/client').then(m => m.remoteUrl('catalog'))\`,
          externalType: 'promise'
        },
        cart: {
          external: \`import('@mfe-orchestrator-hub/client').then(m => m.remoteUrl('cart'))\`,
          externalType: 'promise'
        }
      },
      shared: ['react', 'react-dom']
    })
  ]
});`;

type Stat = {value: string; label: string};

const STATS: Stat[] = [
  {value: '3', label: 'Git providers'},
  {value: '3', label: 'Cloud storages'},
  {value: '2', label: 'Bundlers'},
  {value: '∞', label: 'Environments'},
  {value: '1 click', label: 'Rollback'},
];

type Card = {
  icon: string;
  title: string;
  description: string;
  to: string;
  cta?: string;
  badge?: string;
};

const START_HERE: Card[] = [
  {
    icon: '🚀',
    title: 'Quick start',
    description:
      'From zero to a deployed microfrontend — and a one-click rollback — on the free hosted console. About ten minutes, nothing to install.',
    to: '/docs/quick-start',
    cta: 'Start the quick start',
  },
  {
    icon: '🧠',
    title: 'Core concepts',
    description:
      'Projects, environments, microfrontends, deployments and how they relate. The ten minutes that save you an hour later.',
    to: '/docs/core-concepts',
    cta: 'Read the model',
  },
  {
    icon: '🔧',
    title: 'Run it yourself',
    description:
      'Install the platform on your own infrastructure with Docker, Docker Compose, Terraform or Helm.',
    to: '/docs/self-hosting/docker',
    cta: 'Installation guides',
  },
];

const CAPABILITIES: Card[] = [
  {
    icon: '🧩',
    title: 'Generated Module Federation config',
    description:
      'Declare which host loads which remotes and the console produces the Vite or Webpack configuration, with URLs pointing at what is deployed.',
    to: '/docs/integration/overview',
  },
  {
    icon: '📦',
    title: 'Immutable deployments',
    description:
      'A deployment is a snapshot of every microfrontend, variable and storage setting. Editing is not deploying: drafts stay drafts until you deploy.',
    to: '/docs/deployments/overview',
  },
  {
    icon: '⏪',
    title: 'Rollback and redeploy',
    description:
      'Reactivate a previous snapshot without rebuilding or re-tagging. The version that was live yesterday is still there.',
    to: '/docs/deployments/rollback-and-redeploy',
  },
  {
    icon: '🌍',
    title: 'Environments and domains',
    description:
      'As many stages as you need. Allowed domains resolve the environment per request, so one artifact can serve all of them.',
    to: '/docs/environments/domains',
  },
  {
    icon: '🎛️',
    title: 'Runtime configuration',
    description:
      'Per-environment variables served to the browser at boot, so the same build talks to the right API without a rebuild.',
    to: '/docs/integration/runtime-configuration',
  },
  {
    icon: '☁️',
    title: 'Hosting options',
    description:
      'Keep artifacts on the hub, in your own S3, Azure Blob or Google Cloud Storage bucket, or on a CDN you already run.',
    to: '/docs/buckets/overview',
  },
];

type Step = {
  title: string;
  description: string;
  to: string;
};

const STEPS: Step[] = [
  {
    title: 'Connect a repository',
    description:
      'GitHub, GitLab or Azure DevOps. Your code stays with your provider.',
    to: '/docs/repositories/connect/github',
  },
  {
    title: 'Create a microfrontend',
    description:
      'Pick a template and the platform creates the repository, the configuration and the pipeline.',
    to: '/docs/microfrontends/create-a-microfrontend',
  },
  {
    title: 'Publish a version',
    description:
      'Push a tag. The pipeline builds and uploads the artifact where you configured it.',
    to: '/docs/microfrontends/versions-and-builds',
  },
  {
    title: 'Deploy and integrate',
    description:
      'Snapshot the environment, then copy the generated configuration into your host.',
    to: '/docs/deployments/overview',
  },
];

type DocSection = {
  title: string;
  links: {label: string; to: string}[];
};

const DOC_SECTIONS: DocSection[] = [
  {
    title: 'Getting started',
    links: [
      {label: 'Quick start', to: '/docs/quick-start'},
      {label: "Let's start", to: '/docs/intro'},
      {label: 'Core concepts', to: '/docs/core-concepts'},
      {label: 'Templates library', to: '/docs/templates/templates-library'},
    ],
  },
  {
    title: 'Microfrontends',
    links: [
      {label: 'Overview', to: '/docs/microfrontends/overview'},
      {
        label: 'Create a microfrontend',
        to: '/docs/microfrontends/create-a-microfrontend',
      },
      {label: 'Hosts and remotes', to: '/docs/microfrontends/host-and-remotes'},
      {
        label: 'Versions and builds',
        to: '/docs/microfrontends/versions-and-builds',
      },
      {label: 'Hosting options', to: '/docs/microfrontends/hosting-options'},
      {label: 'Canary releases', to: '/docs/microfrontends/canary-releases'},
    ],
  },
  {
    title: 'Environments',
    links: [
      {label: 'Overview', to: '/docs/environments/overview'},
      {label: 'Allowed domains', to: '/docs/environments/domains'},
      {
        label: 'Environment variables',
        to: '/docs/environments/environment-variables',
      },
    ],
  },
  {
    title: 'Deployments',
    links: [
      {label: 'Overview', to: '/docs/deployments/overview'},
      {
        label: 'Rollback and redeploy',
        to: '/docs/deployments/rollback-and-redeploy',
      },
      {label: 'Build status', to: '/docs/deployments/build-status'},
    ],
  },
  {
    title: 'Integration',
    links: [
      {label: 'Overview', to: '/docs/integration/overview'},
      {label: 'Vite', to: '/docs/integration/module-federation-vite'},
      {label: 'Webpack', to: '/docs/integration/module-federation-webpack'},
      {
        label: 'Runtime configuration',
        to: '/docs/integration/runtime-configuration',
      },
      {label: 'Serve API', to: '/docs/integration/serve-api'},
    ],
  },
  {
    title: 'Storage',
    links: [
      {label: 'Overview', to: '/docs/buckets/overview'},
      {label: 'AWS S3', to: '/docs/buckets/aws-s3'},
      {label: 'Azure Blob Storage', to: '/docs/buckets/azure-blob-storage'},
      {
        label: 'Google Cloud Storage',
        to: '/docs/buckets/google-cloud-storage',
      },
    ],
  },
  {
    title: 'Repositories',
    links: [
      {label: 'GitHub', to: '/docs/repositories/connect/github'},
      {label: 'GitLab', to: '/docs/repositories/connect/gitlab'},
      {label: 'Azure DevOps', to: '/docs/repositories/connect/azure.dev-ops'},
    ],
  },
  {
    title: 'CI/CD',
    links: [
      {label: 'API keys', to: '/docs/ci-cd/api-keys'},
      {label: 'GitHub Actions', to: '/docs/ci-cd/github-actions'},
      {label: 'GitLab CI', to: '/docs/ci-cd/gitlab-ci'},
      {label: 'Azure Pipelines', to: '/docs/ci-cd/azure-pipelines'},
      {label: 'Manual upload', to: '/docs/ci-cd/manual-upload'},
    ],
  },
  {
    title: 'Project settings',
    links: [
      {label: 'Projects', to: '/docs/project-settings/projects'},
      {label: 'Users and roles', to: '/docs/project-settings/users-and-roles'},
    ],
  },
  {
    title: 'Self-hosting',
    links: [
      {label: 'Docker', to: '/docs/self-hosting/docker'},
      {label: 'Docker Compose', to: '/docs/self-hosting/docker-compose'},
      {label: 'Terraform', to: '/docs/self-hosting/terraform'},
      {label: 'Helm (Kubernetes)', to: '/docs/self-hosting/helm'},
      {
        label: 'Environment variables',
        to: '/docs/self-hosting/environment-variables',
      },
      {
        label: 'External resources',
        to: '/docs/self-hosting/use-external-resources',
      },
    ],
  },
];

function Hero() {
  return (
    <header className={styles.hero}>
      <div className={styles.heroGlow} aria-hidden="true" />
      <div className={styles.heroInner}>
        <div className={styles.heroCopy}>
          <span className={styles.eyebrow}>Documentation</span>
          <Heading as="h1" className={styles.heroTitle}>
            The <span className={styles.gradientText}>control plane</span> for
            your microfrontends
          </Heading>
          <p className={styles.heroSubtitle}>
            MFE Orchestrator keeps versions, environments, deployments and
            rollbacks of a microfrontend architecture in one place — and
            generates the Module Federation configuration your host application
            needs. These pages cover both the hosted console and the
            self-hosted platform.
          </p>
          <div className={styles.heroActions}>
            <Link className={styles.buttonPrimary} to="/docs/quick-start">
              Quick start →
            </Link>
            <Link className={styles.buttonGhost} to="/docs/core-concepts">
              Core concepts
            </Link>
            <Link className={styles.buttonQuiet} to={CONSOLE_URL}>
              Open the console ↗
            </Link>
          </div>
          <ul className={styles.heroNotes}>
            <li>Hosted console or self-hosted</li>
            <li>GitHub, GitLab and Azure DevOps</li>
            <li>Vite and Webpack</li>
          </ul>
        </div>
        <div className={styles.heroVisual}>
          <div className={styles.codeCard}>
            <div className={styles.codeCardBar}>
              <span className={styles.dot} data-dot="red" />
              <span className={styles.dot} data-dot="amber" />
              <span className={styles.dot} data-dot="green" />
              <span className={styles.codeCardTitle}>Integration</span>
            </div>
            <CodeBlock language="js" className={styles.codeBlock}>
              {HOST_CONFIG}
            </CodeBlock>
          </div>
        </div>
      </div>
      <div className={styles.statsStrip}>
        {STATS.map((stat) => (
          <div className={styles.stat} key={stat.label}>
            <span className={styles.statValue}>{stat.value}</span>
            <span className={styles.statLabel}>{stat.label}</span>
          </div>
        ))}
      </div>
    </header>
  );
}

function EntryCard({icon, title, description, to, cta, badge}: Card) {
  return (
    <Link className={styles.featureCard} to={to}>
      <span className={styles.featureIcon} aria-hidden="true">
        {icon}
      </span>
      <h3 className={styles.featureTitle}>
        {title}
        {badge && <span className={styles.featureBadge}>{badge}</span>}
      </h3>
      <p className={styles.featureDescription}>{description}</p>
      <span className={styles.featureLink}>{cta ?? 'Read the docs'} →</span>
    </Link>
  );
}

function StartHere() {
  return (
    <section className={styles.section}>
      <div className={styles.sectionHead}>
        <span className={styles.kicker}>Start here</span>
        <Heading as="h2" className={styles.sectionTitle}>
          Three ways in
        </Heading>
        <p className={styles.sectionLead}>
          Depending on whether you want to try the platform, understand it, or
          run it on your own infrastructure.
        </p>
      </div>
      <div className={styles.featureGrid}>
        {START_HERE.map((card) => (
          <EntryCard key={card.title} {...card} />
        ))}
      </div>
    </section>
  );
}

function Capabilities() {
  return (
    <section className={styles.sectionAlt}>
      <div className={styles.sectionInner}>
        <div className={styles.sectionHead}>
          <span className={styles.kicker}>What the platform does</span>
          <Heading as="h2" className={styles.sectionTitle}>
            Everything a microfrontend needs after <code>npm run build</code>
          </Heading>
          <p className={styles.sectionLead}>
            Not a bundler and not a framework — the layer that decides what is
            live, where, and for whom.
          </p>
        </div>
        <div className={styles.featureGrid}>
          {CAPABILITIES.map((card) => (
            <EntryCard key={card.title} {...card} />
          ))}
        </div>
      </div>
    </section>
  );
}

function HowItWorks() {
  return (
    <section className={styles.section}>
      <div className={styles.sectionHead}>
        <span className={styles.kicker}>The short path</span>
        <Heading as="h2" className={styles.sectionTitle}>
          From empty project to live microfrontend
        </Heading>
        <p className={styles.sectionLead}>
          Four steps, each with a guide. The console handles the plumbing in
          between.
        </p>
      </div>
      <ol className={styles.steps}>
        {STEPS.map((step, index) => (
          <li className={styles.step} key={step.title}>
            <span className={styles.stepNumber}>{index + 1}</span>
            <div>
              <h3 className={styles.stepTitle}>{step.title}</h3>
              <p className={styles.stepDescription}>{step.description}</p>
              <Link className={styles.inlineLink} to={step.to}>
                Read the guide →
              </Link>
            </div>
          </li>
        ))}
      </ol>
    </section>
  );
}

function DocIndex() {
  return (
    <section className={styles.sectionAlt}>
      <div className={styles.sectionInner}>
        <div className={styles.sectionHead}>
          <span className={styles.kicker}>Reference</span>
          <Heading as="h2" className={styles.sectionTitle}>
            Browse the documentation
          </Heading>
          <p className={styles.sectionLead}>
            Every section of the manual, one click away.
          </p>
        </div>
        <div className={styles.docGrid}>
          {DOC_SECTIONS.map((section) => (
            <div className={styles.docColumn} key={section.title}>
              <h3 className={styles.docColumnTitle}>{section.title}</h3>
              <ul className={styles.docList}>
                {section.links.map((link) => (
                  <li key={link.to}>
                    <Link to={link.to}>{link.label}</Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

const LOGOS = [
  {src: 'img/logos/vite-logo.png', alt: 'Vite'},
  {src: 'img/logos/webpack-logo.png', alt: 'Webpack'},
  {src: 'img/logos/webcomponents.png', alt: 'Web Components'},
];

function Logo({src, alt}: {src: string; alt: string}) {
  return (
    <span className={styles.logoChip} title={alt}>
      <img className={styles.logo} src={useBaseUrl(src)} alt={alt} />
    </span>
  );
}

function Ecosystem() {
  return (
    <section className={styles.sectionNarrow}>
      <p className={styles.ecosystemLabel}>
        Templates ship for Vite, Webpack and Web Components. The platform itself
        serves whatever your build produces.
      </p>
      <div className={styles.logoRow}>
        {LOGOS.map((logo) => (
          <Logo key={logo.alt} {...logo} />
        ))}
      </div>
      <Link className={styles.inlineLink} to="/docs/templates/templates-library">
        See the templates library →
      </Link>
    </section>
  );
}

function Hosting() {
  return (
    <section className={styles.section}>
      <div className={styles.sectionHead}>
        <span className={styles.kicker}>Two ways to run it</span>
        <Heading as="h2" className={styles.sectionTitle}>
          Hosted console or your own infrastructure
        </Heading>
      </div>
      <div className={styles.planGrid}>
        <div className={styles.planCard}>
          <h3 className={styles.planTitle}>Hosted console</h3>
          <p className={styles.planSubtitle}>
            Nothing to install, always up to date
          </p>
          <ul className={styles.checkList}>
            <li>Sign in with email or Google SSO</li>
            <li>Artifacts on the hub, or in your own bucket</li>
            <li>Used throughout the tutorial</li>
          </ul>
          <Link className={styles.buttonGhostBlock} to={CONSOLE_URL}>
            Open the console ↗
          </Link>
        </div>
        <div className={styles.planCard}>
          <h3 className={styles.planTitle}>Self-hosted</h3>
          <p className={styles.planSubtitle}>Your infrastructure, your data</p>
          <ul className={styles.checkList}>
            <li>Docker, Docker Compose, Terraform or Helm</li>
            <li>Bring your own MongoDB and object storage</li>
            <li>SSO with Auth0, Microsoft Entra or Google</li>
          </ul>
          <Link
            className={styles.buttonGhostBlock}
            to="/docs/self-hosting/docker">
            Installation guides →
          </Link>
        </div>
      </div>
    </section>
  );
}

function Help() {
  return (
    <section className={styles.sectionNarrow}>
      <div className={styles.helpPanel}>
        <div>
          <h2 className={styles.helpTitle}>Not sure where to start?</h2>
          <p className={styles.helpText}>
            The quick start takes you from an empty account to a deployed
            microfrontend — and back with a rollback. If something is missing or
            wrong in these pages, open an issue — every page has an “Edit this
            page” link at the bottom.
          </p>
        </div>
        <div className={styles.helpActions}>
          <Link className={styles.buttonPrimary} to="/docs/quick-start">
            Quick start →
          </Link>
          <Link className={styles.buttonGhost} to={GITHUB_URL}>
            GitHub ↗
          </Link>
        </div>
      </div>
    </section>
  );
}

export default function Home(): ReactNode {
  return (
    <Layout
      title="The control plane for your microfrontends"
      description="Documentation for MFE Orchestrator: the control plane for microfrontend architectures — versions, environments, deployments, rollback and generated Module Federation configuration, hosted or self-hosted.">
      <Head>
        <meta property="og:type" content="website" />
        <meta name="robots" content="index, follow, max-image-preview:large" />
        <script type="application/ld+json">
          {JSON.stringify(STRUCTURED_DATA)}
        </script>
      </Head>
      <Hero />
      <main>
        <StartHere />
        <Capabilities />
        <HowItWorks />
        <DocIndex />
        <Ecosystem />
        <Hosting />
        <Help />
      </main>
    </Layout>
  );
}
