import type {ReactNode} from 'react';
import Link from '@docusaurus/Link';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';
import CodeBlock from '@theme/CodeBlock';
import useBaseUrl from '@docusaurus/useBaseUrl';
import styles from './index.module.css';

const CONSOLE_URL = 'https://console.mfe-orchestrator.dev';
const GITHUB_URL = 'https://github.com/mfe-orchestrator';

const HOST_CONFIG = `// vite.config.js — generated by MFE Orchestrator
import federation from '@originjs/vite-plugin-federation';

export default defineConfig({
  plugins: [
    federation({
      name: 'shell',
      remotes: {
        catalog: '<API_BASE>/serve/mfe/files/auto/.../catalog',
        cart:    '<API_BASE>/serve/mfe/files/auto/.../cart',
      },
      shared: ['react', 'react-dom'],
    }),
  ],
});`;

const RUNTIME_CONFIG = `<!-- one build, configured per environment -->
<script src="<API_BASE>/serve/global-variables/<envId>/index.js">
</script>

<script>
  // ready before your bundle runs — no loading state
  window.globalConfig.API_URL // → https://api.example.com
</script>`;

type Stat = {value: string; label: string};

const STATS: Stat[] = [
  {value: '3', label: 'Git providers'},
  {value: '3', label: 'Cloud storages'},
  {value: '2', label: 'Bundlers'},
  {value: '∞', label: 'Environments'},
  {value: '1 click', label: 'Rollback'},
];

type Feature = {
  icon: string;
  title: string;
  description: string;
  to: string;
  badge?: string;
};

const FEATURES: Feature[] = [
  {
    icon: '🧩',
    title: 'Module Federation, generated',
    description:
      'Declare which host loads which remotes, and the console writes the exact Vite or Webpack configuration for you — with real URLs, already pointing at what is deployed.',
    to: '/docs/integration/overview',
  },
  {
    icon: '📦',
    title: 'Immutable deployments',
    description:
      'A deployment is a snapshot of every microfrontend, variable and storage setting. Editing is not deploying: your drafts never leak into production by accident.',
    to: '/docs/deployments/overview',
  },
  {
    icon: '⏪',
    title: 'Rollback in seconds',
    description:
      'A bad release is one click away from being yesterday’s release. Reactivate any previous snapshot without rebuilding or re-tagging anything.',
    to: '/docs/deployments/rollback-and-redeploy',
  },
  {
    icon: '🌍',
    title: 'One build, every stage',
    description:
      'Dev, UAT, production and as many stages as you need. Allowed domains resolve the right environment per request, so a single artifact serves them all.',
    to: '/docs/environments/domains',
  },
  {
    icon: '🎛️',
    title: 'Runtime configuration',
    description:
      'Change API URLs and feature flags per environment and have them live immediately — no rebuild, no redeploy of your host application.',
    to: '/docs/integration/runtime-configuration',
  },
  {
    icon: '☁️',
    title: 'Bring your own storage',
    description:
      'Keep artifacts on the hub, in your own AWS S3, Azure Blob or Google Cloud Storage bucket, or on the CDN you already pay for. Your files, your rules.',
    to: '/docs/buckets/overview',
  },
];

const SECONDARY_FEATURES: Feature[] = [
  {
    icon: '⚡',
    title: 'Templates that ship',
    description:
      'Pick a template, get a repository with a working build and a pipeline already wired.',
    to: '/docs/templates/templates-library',
  },
  {
    icon: '🔁',
    title: 'CI/CD native',
    description:
      'API keys plus ready-made pipelines for GitHub Actions, GitLab CI and Azure Pipelines.',
    to: '/docs/ci-cd/api-keys',
  },
  {
    icon: '🐤',
    title: 'Canary releases',
    description:
      'Serve a new version to a slice of traffic, without touching your host application.',
    to: '/docs/microfrontends/canary-releases',
    badge: 'Experimental',
  },
  {
    icon: '👥',
    title: 'Teams and roles',
    description:
      'Admin, Editor and Viewer per project — invite the whole team without handing over the keys.',
    to: '/docs/project-settings/users-and-roles',
  },
];

type Step = {
  title: string;
  description: string;
  to: string;
};

const STEPS: Step[] = [
  {
    title: 'Connect your repository',
    description:
      'GitHub, GitLab or Azure DevOps. Your code never leaves your own provider.',
    to: '/docs/repositories/connect/github',
  },
  {
    title: 'Create a microfrontend',
    description:
      'Choose a template and the platform creates the repo, the configuration and the pipeline.',
    to: '/docs/microfrontends/create-a-microfrontend',
  },
  {
    title: 'Publish a version',
    description:
      'Push a tag. The pipeline builds and uploads the artifact where you told it to.',
    to: '/docs/microfrontends/versions-and-builds',
  },
  {
    title: 'Deploy and integrate',
    description:
      'Snapshot the environment, copy the generated configuration into your host, and you are live.',
    to: '/docs/deployments/overview',
  },
];

const PAINS: string[] = [
  'Remote URLs hardcoded in five host repositories',
  'A version bump means a host rebuild and a coordinated release',
  'Nobody is quite sure which version production is actually serving',
  'Rolling back means reverting commits and waiting for CI',
];

const GAINS: string[] = [
  'One console holds the whole graph of hosts and remotes',
  'Bump a version, deploy the environment — the host stays untouched',
  'Every environment shows its active deployment, down to the variable',
  'Rollback is reactivating the previous snapshot: seconds, not commits',
];

function Hero() {
  return (
    <header className={styles.hero}>
      <div className={styles.heroGlow} aria-hidden="true" />
      <div className={styles.heroInner}>
        <div className={styles.heroCopy}>
          <span className={styles.eyebrow}>
            Open source · Module Federation native
          </span>
          <Heading as="h1" className={styles.heroTitle}>
            Microfrontends, <span className={styles.gradientText}>finally
            under control</span>.
          </Heading>
          <p className={styles.heroSubtitle}>
            MFE Orchestrator is the control plane for microfrontend
            architectures: versions, environments, deployments and rollbacks in
            one console — for React, Angular or anything else your teams ship.
          </p>
          <div className={styles.heroActions}>
            <Link className={styles.buttonPrimary} to={CONSOLE_URL}>
              Start free →
            </Link>
            <Link className={styles.buttonGhost} to="/docs/intro">
              Get started in 5 min
            </Link>
          </div>
          <ul className={styles.heroNotes}>
            <li>Free hosted console</li>
            <li>Self-host with Docker or Terraform</li>
            <li>No lock-in: your code stays in your repo</li>
          </ul>
        </div>
        <div className={styles.heroVisual}>
          <div className={styles.codeCard}>
            <div className={styles.codeCardBar}>
              <span className={styles.dot} data-dot="red" />
              <span className={styles.dot} data-dot="amber" />
              <span className={styles.dot} data-dot="green" />
              <span className={styles.codeCardTitle}>Integration</span>
            </div>
            <CodeBlock language="js" className={styles.codeBlock}>
              {HOST_CONFIG}
            </CodeBlock>
          </div>
        </div>
      </div>
      <div className={styles.statsStrip}>
        {STATS.map((stat) => (
          <div className={styles.stat} key={stat.label}>
            <span className={styles.statValue}>{stat.value}</span>
            <span className={styles.statLabel}>{stat.label}</span>
          </div>
        ))}
      </div>
    </header>
  );
}

function ValueProp() {
  return (
    <section className={styles.section}>
      <div className={styles.sectionHead}>
        <span className={styles.kicker}>Why it exists</span>
        <Heading as="h2" className={styles.sectionTitle}>
          Microfrontends scale teams. Then they stop scaling.
        </Heading>
        <p className={styles.sectionLead}>
          Splitting the frontend is the easy part. What breaks is everything
          around it: who serves which version, in which environment, and how you
          get back when it goes wrong.
        </p>
      </div>
      <div className={styles.compare}>
        <div className={styles.compareCard} data-tone="pain">
          <h3 className={styles.compareTitle}>Without a control plane</h3>
          <ul className={styles.compareList}>
            {PAINS.map((item) => (
              <li key={item}>
                <span className={styles.markPain} aria-hidden="true">
                  ✕
                </span>
                {item}
              </li>
            ))}
          </ul>
        </div>
        <div className={styles.compareCard} data-tone="gain">
          <h3 className={styles.compareTitle}>With MFE Orchestrator</h3>
          <ul className={styles.compareList}>
            {GAINS.map((item) => (
              <li key={item}>
                <span className={styles.markGain} aria-hidden="true">
                  ✓
                </span>
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}

function FeatureCard({icon, title, description, to, badge}: Feature) {
  return (
    <Link className={styles.featureCard} to={to}>
      <span className={styles.featureIcon} aria-hidden="true">
        {icon}
      </span>
      <h3 className={styles.featureTitle}>
        {title}
        {badge && <span className={styles.featureBadge}>{badge}</span>}
      </h3>
      <p className={styles.featureDescription}>{description}</p>
      <span className={styles.featureLink}>Learn more →</span>
    </Link>
  );
}

function Features() {
  return (
    <section className={styles.section}>
      <div className={styles.sectionHead}>
        <span className={styles.kicker}>Platform</span>
        <Heading as="h2" className={styles.sectionTitle}>
          Everything a microfrontend needs after <code>npm run build</code>
        </Heading>
        <p className={styles.sectionLead}>
          Not a bundler, not a framework. The layer that decides what is live,
          where, and for whom.
        </p>
      </div>
      <div className={styles.featureGrid}>
        {FEATURES.map((feature) => (
          <FeatureCard key={feature.title} {...feature} />
        ))}
      </div>
      <div className={styles.featureGridSmall}>
        {SECONDARY_FEATURES.map((feature) => (
          <FeatureCard key={feature.title} {...feature} />
        ))}
      </div>
    </section>
  );
}

function HowItWorks() {
  return (
    <section className={styles.sectionAlt}>
      <div className={styles.sectionInner}>
        <div className={styles.sectionHead}>
          <span className={styles.kicker}>How it works</span>
          <Heading as="h2" className={styles.sectionTitle}>
            From empty project to live microfrontend
          </Heading>
          <p className={styles.sectionLead}>
            Four steps. The console does the plumbing you would otherwise write
            by hand.
          </p>
        </div>
        <ol className={styles.steps}>
          {STEPS.map((step, index) => (
            <li className={styles.step} key={step.title}>
              <span className={styles.stepNumber}>{index + 1}</span>
              <div>
                <h3 className={styles.stepTitle}>{step.title}</h3>
                <p className={styles.stepDescription}>{step.description}</p>
                <Link className={styles.inlineLink} to={step.to}>
                  Read the guide →
                </Link>
              </div>
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
}

function RuntimeSection() {
  return (
    <section className={styles.section}>
      <div className={styles.split}>
        <div>
          <span className={styles.kicker}>Build once</span>
          <Heading as="h2" className={styles.sectionTitleLeft}>
            Stop rebuilding to change a URL
          </Heading>
          <p className={styles.sectionLeadLeft}>
            Environment variables live in the platform and are served to the
            browser at boot. The same artifact that runs in UAT runs in
            production — pointing at the right API, with the right flags on.
          </p>
          <ul className={styles.checkList}>
            <li>Per-environment values, resolved from the active deployment</li>
            <li>Blocking script in <code>&lt;head&gt;</code>: no loading state, no race</li>
            <li>Or fetch the whole environment in a single API call</li>
          </ul>
          <Link className={styles.buttonPrimary} to="/docs/integration/runtime-configuration">
            See the integration guide →
          </Link>
        </div>
        <div className={styles.codeCard}>
          <div className={styles.codeCardBar}>
            <span className={styles.dot} data-dot="red" />
            <span className={styles.dot} data-dot="amber" />
            <span className={styles.dot} data-dot="green" />
            <span className={styles.codeCardTitle}>index.html</span>
          </div>
          <CodeBlock language="html" className={styles.codeBlock}>
            {RUNTIME_CONFIG}
          </CodeBlock>
        </div>
      </div>
    </section>
  );
}

const LOGOS = [
  {src: 'img/logos/vite-logo.png', alt: 'Vite'},
  {src: 'img/logos/webpack-logo.png', alt: 'Webpack'},
  {src: 'img/logos/single-spa.png', alt: 'single-spa'},
  {src: 'img/logos/webcomponents.png', alt: 'Web Components'},
];

function Logo({src, alt}: {src: string; alt: string}) {
  return (
    <span className={styles.logoChip} title={alt}>
      <img className={styles.logo} src={useBaseUrl(src)} alt={alt} />
    </span>
  );
}

function Ecosystem() {
  return (
    <section className={styles.sectionNarrow}>
      <p className={styles.ecosystemLabel}>
        Framework agnostic. Works with the tools you already chose.
      </p>
      <div className={styles.logoRow}>
        {LOGOS.map((logo) => (
          <Logo key={logo.alt} {...logo} />
        ))}
      </div>
    </section>
  );
}

function Hosting() {
  return (
    <section className={styles.sectionAlt}>
      <div className={styles.sectionInner}>
        <div className={styles.sectionHead}>
          <span className={styles.kicker}>Two ways to run it</span>
          <Heading as="h2" className={styles.sectionTitle}>
            Hosted for speed, self-hosted for control
          </Heading>
        </div>
        <div className={styles.planGrid}>
          <div className={styles.planCard} data-featured="true">
            <span className={styles.planTag}>Recommended</span>
            <h3 className={styles.planTitle}>Cloud console</h3>
            <p className={styles.planPrice}>
              Free to start<span>no installation</span>
            </p>
            <ul className={styles.checkList}>
              <li>Nothing to install, always up to date</li>
              <li>Sign in with email or Google SSO</li>
              <li>Artifacts on the hub, or in your own bucket</li>
              <li>First microfrontend live in minutes</li>
            </ul>
            <Link className={styles.buttonPrimaryBlock} to={CONSOLE_URL}>
              Open the console →
            </Link>
          </div>
          <div className={styles.planCard}>
            <span className={styles.planTagMuted}>Open source</span>
            <h3 className={styles.planTitle}>Self-hosted</h3>
            <p className={styles.planPrice}>
              Your infrastructure<span>your data, your network</span>
            </p>
            <ul className={styles.checkList}>
              <li>Docker, Docker Compose or Terraform</li>
              <li>Bring your own MongoDB and object storage</li>
              <li>SSO with Auth0, Microsoft Entra or Google</li>
              <li>Air-gapped and on-prem friendly</li>
            </ul>
            <Link className={styles.buttonGhostBlock} to="/docs/self-hosting/docker">
              Installation options →
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

function FinalCta() {
  return (
    <section className={styles.ctaBand}>
      <div className={styles.ctaInner}>
        <Heading as="h2" className={styles.ctaTitle}>
          Your next release does not have to be a coordination meeting.
        </Heading>
        <p className={styles.ctaLead}>
          Connect a repository, create a microfrontend from a template, deploy.
          You will know whether this fits your architecture before your coffee
          gets cold.
        </p>
        <div className={styles.ctaActions}>
          <Link className={styles.buttonPrimary} to={CONSOLE_URL}>
            Start free →
          </Link>
          <Link className={styles.buttonGhost} to="/docs/intro">
            Read the docs
          </Link>
          <Link className={styles.buttonGhost} to={GITHUB_URL}>
            Star on GitHub
          </Link>
        </div>
      </div>
    </section>
  );
}

export default function Home(): ReactNode {
  return (
    <Layout
      title="Microfrontends, finally under control"
      description="MFE Orchestrator is the control plane for microfrontend architectures: versions, environments, immutable deployments, one-click rollback and generated Module Federation configuration — hosted or self-hosted.">
      <Hero />
      <main>
        <ValueProp />
        <Features />
        <HowItWorks />
        <RuntimeSection />
        <Ecosystem />
        <Hosting />
        <FinalCta />
      </main>
    </Layout>
  );
}
